language: java

sudo: false

addons:
  hosts:
    - db

services:
  - docker

install:
  - docker build -t database db/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      install: skip
      script: mvn test -Dtest=com.napier.sem.AppTest+CityTest+CountryTest
    - stage: integration tests
      script: mvn test -Dtest=com.napier.sem.AppIntegrationTest
    - stage: deploy
      install: skip
      script:
        - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
        - docker-compose up --abort-on-container-exit


stages:
  - unit tests
  - integration tests
  - name: deploy
    if: branch = master
